backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {
          label: "Types",
          name: "types",
          widget: "select",
          multiple: true,
          options: ["Review", "Playthrough", "Strategy Guide"]
        }

  - name: "game"
    label: "Game"
    folder: "src/pages/game"
    create: true
    slug: "{{slug}}"
    fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "game"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Release Date", name: "releaseDate", widget: "date"}
    - {label: "Rating", name: "rating", widget: "select", options: ["1", "2", "3", "4", "5"]}
    - {label: "Platform", name: "platform", widget: "select", multiple: true, options: ["Xbox", "Playstation", "PC"]}
    - {label: "Image", name: 'image', widget: "image"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
